name: StarTool
main: top.starwish.startool.StarToolMain
version: 0.1.1
author: StarWish

commands:
   startool:
     description: “插件主命令”
     aliases: [stool]
   biu:
     description: "元首的愤怒"
permissions:
   startool.uuid:
     default: op
   startool.version:
     default: op
   startool.clearscreen:
     default: op 
   startool.biu:
     default: op  
