name: StarTool
main: top.starwish.startool.startup.StarToolStartup
version: 0.1.5-SNAPSHOT
description: "一个简单实用的小插件"
author: StarWish_Sama

commands:
   startool:
     description: “插件主命令”
     aliases: [stool]
   curse:
     description: "诅咒一个玩家!"
   laba:
     description: "可以发送全服公告"
     aliases: [lb]
permissions:
   startool.uuid:
     default: op
   startool.version:
     default: true
   startool.clearscreen:
     default: op
   startool.clearscreen.other:
     default: op
   startool.curse.use:
     default: op
   startool.curse.other:
     default: op
   startool.laba:
     default: true
   startool.laba.bypass:
     default: op