main: io.github.starwishsama.StarTool.StarToolMain
name: StarTool
version: 1.0.3-RELEASE
softdepend: [ProtocolLib]
api-version: 1.13

commands:
  startool:
    description: The main command of StarTool
    aliases: stool
  at:
    description: at
  sgc:
    description: gc
    aliases:
      - startoolgc
      - stgc
      - stoolgc
  srestart:
    description: restart server
  dustbin:
    description: dustbin
    aliases:
      - trashcan
      - db
      - tc
permissions:
  startool.reload:
    default: op
  startool.colorsign:
    default: op
  startool.at.all:
    default: op
  startool.at.notify:
    default: true
  startool.clearscreen:
    default: op
  startool.clearscreen.other:
    default: op
  startool.commands.gc:
    default: op
  startool.commands.restart:
    default: op