#####################
# StarTool 配置文件 #
#####################
# 使用 /laba 指令发送消息时需收取玩家多少费用? (默认为50游戏币)
LabaPrice: 100
# 是否启用小喇叭功能? 需要 Vault 插件作为前置 (默认为true, 改为false以关闭)
EnableLaba: true
# 是否打开聊天栏世界前缀? (默认为true, 改为false以关闭)
EnableChatPrefix: true
# 治愈诅咒的价格
HealCursePrice: 120
# 自动转换为当前坐标的关键字
PosText: pos
# 是否启用聊天发送坐标
PosTranslate: true
# 玩家加入服务器时发送的文字
PlayerJoinMessage: "&b欢迎来到服务器!"