name: StarTool
main: top.starwish.StarTool.StarToolStartup
version: 0.1.7.2-SNAPSHOT
description: "一个简单实用的小插件"
author: StarWish_Sama
api-version: 1.13

commands:
   startool:
     description: "插件主命令"
     aliases: [stool, sto]
   curse:
     description: "诅咒一个玩家!"
   laba:
     description: "可以发送全服公告"
     aliases: [lb]
   gc:
     description: "显示服务器信息"
permissions:
   startool.uuid:
     default: op
   startool.version:
     default: true
   startool.clearscreen:
     default: op
   startool.clearscreen.other:
     default: op
   startool.curse.use:
     default: op
   startool.curse.anticurse:
     default: op
   startool.curse.restore:
     default: true
   startool.laba:
     default: true
   startool.laba.bypass:
     default: op
   startool.commands.gc:
     default: op