name: StarTool
main: io.github.starwishsama.StarTool.StarToolStartup
version: 1.0.0-RELEASE
description: "一个简单实用的小插件"
author: StarWish_Sama
api-version: 1.13

commands:
   startool:
     description: "插件主命令"
     aliases: [stool, sto]
   curse:
     description: "诅咒一个玩家!"
     aliases: [biu]
   laba:
     description: "可以发送全服公告"
     aliases: [lb]
   gc:
     description: "显示服务器信息"
   tpa:
     description: "传送"
   tpaccept:
     description: ""
     aliases:
       - tpyes
   tpdeny:
     description: ""
     aliases:
       - tpno
   home:
     description: "传送"
   gm:
     description: "改变游戏模式"
   enderchest:
     description: enderchest
     aliases:
       - ec
       - echest
   msg:
     description: send msg to other player
     aliases:
       - message
       - tell
   debug:
    description: debug
   back:
    description: back
   bed:
     description: bed
   sethome:
     description: sethome
permissions:
   startool.uuid:
     default: op
   startool.clearscreen:
     default: op
   startool.clearscreen.other:
     default: op
   startool.commands.curse.use:
     default: op
   startool.commands.curse.anticurse:
     default: op
   startool.curse.restore:
     default: true
   startool.laba:
     default: true
   startool.laba.bypass:
     default: op
   startool.commands.gc:
     default: op
   startool.commands.reload:
     default: op
   startool.commands.version:
     default: true
   startool.commands.teleport.tpa:
     default: true
   startool.commands.gamemode:
     default: op
     children:
       - startool.commands.gamemode.other
       - startool.commands.gamemode.use
   startool.commands.debug:
     default: op